server:
  port: 8080
  
spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
  application:
    name: JODConverter Sample Spring Boot 

jodconverter:
  local:
    enabled: true
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages
